### ISSUE TITLE
Support for old backup files

### ISSUE THREAD

**Issue by neizod** [mvarnagiris/financius#162]
Create backup in KitKat, then upgrade Android (Nexus 5) to Lollipop, restore from Google Drive not work.

**Comment by mvarnagiris** [comment]
For now you can't restore old backups, but I suppose I should add that support. I'll do it for next release

**Comment by supergillis** [comment]
Same issue here. Upgraded to Lollipop and want to continue to keep track of my expenses...

**Comment by mvarnagiris** [comment]
I'll work on this for next release as this might become an issue

**Comment by mvarnagiris** [comment]
I've checked the old backup format. It would be too hard to make it work with the new app. Will not be doing that now as it would take too long.

**Comment by supergillis** [comment]
I understand that the formats might be too different, but this really is an essential feature.

Do you happen to have any specification of the old and the new export format? Or only a specification of the new export format? I'll write a conversion tool myself then.

**Comment by mvarnagiris** [comment]
I'll reopen the issue. I might do it. The only complication will be duplicates. If you import that backup twice you will have duplicates for everything.

**Comment by supergillis** [comment]
Thanks.

I wrote a Fiddle where you can paste the old backup and generate a new one: http://jsfiddle.net/supergillis/awurxdnv/

I think the generated output is fine as I used https://github.com/mvarnagiris/Financius/blob/HEAD/financius/src/main/java/com/code44/finance/data/backup/BackupDataImporter.java as basis.

When the generated file is imported via "Import backup" it succeeds and toasts "Done". But when loading the main activity Financius crashes with the following error:

```
E/AndroidRuntime(16374): java.lang.IllegalArgumentException: Value 0 is not supported.
E/AndroidRuntime(16374):  at com.code44.finance.common.model.ModelState.fromInt(ModelState.java:30)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:191)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.Currency.fromCurrencyTo(Currency.java:86)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.Account.fromCursor(Account.java:136)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:201)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.Account.fromAccountTo(Account.java:63)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.Transaction.fromCursor(Transaction.java:180)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:201)
E/AndroidRuntime(16374):  at com.code44.finance.data.model.Transaction.from(Transaction.java:66)
E/AndroidRuntime(16374):  at com.code44.finance.ui.overview.OverviewFragment.onTransactionsLoaded(OverviewFragment.java:153)
E/AndroidRuntime(16374):  at com.code44.finance.ui.overview.OverviewFragment.onLoadFinished(OverviewFragment.java:115)
E/AndroidRuntime(16374):  at com.code44.finance.ui.overview.OverviewFragment.onLoadFinished(OverviewFragment.java:43)
E/AndroidRuntime(16374):  at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
E/AndroidRuntime(16374):  at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
E/AndroidRuntime(16374):  at android.support.v4.content.Loader.deliverResult(Loader.java:104)
E/AndroidRuntime(16374):  at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:73)
E/AndroidRuntime(16374):  at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:35)
E/AndroidRuntime(16374):  at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
E/AndroidRuntime(16374):  at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
E/AndroidRuntime(16374):  at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
E/AndroidRuntime(16374):  at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
E/AndroidRuntime(16374):  at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
E/AndroidRuntime(16374):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16374):  at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(16374):  at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(16374):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16374):  at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(16374):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(16374):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Even though my Fiddle sets "model_state" to 1 for every model.

When the file is imported with "Clear and restore" then the import fails and produces the following error:

```
E/AndroidRuntime(17651): java.lang.IllegalArgumentException: Value 0 is not supported.
E/AndroidRuntime(17651):  at com.code44.finance.common.model.ModelState.fromInt(ModelState.java:30)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:191)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.Currency.fromCurrencyTo(Currency.java:86)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.Account.fromCursor(Account.java:136)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:201)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.Account.fromAccountTo(Account.java:63)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.Transaction.fromCursor(Transaction.java:180)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.BaseModel.updateFrom(BaseModel.java:201)
E/AndroidRuntime(17651):  at com.code44.finance.data.model.Transaction.from(Transaction.java:66)
E/AndroidRuntime(17651):  at com.code44.finance.ui.overview.OverviewFragment.onTransactionsLoaded(OverviewFragment.java:153)
E/AndroidRuntime(17651):  at com.code44.finance.ui.overview.OverviewFragment.onLoadFinished(OverviewFragment.java:115)
E/AndroidRuntime(17651):  at com.code44.finance.ui.overview.OverviewFragment.onLoadFinished(OverviewFragment.java:43)
E/AndroidRuntime(17651):  at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
E/AndroidRuntime(17651):  at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
E/AndroidRuntime(17651):  at android.support.v4.content.Loader.deliverResult(Loader.java:104)
E/AndroidRuntime(17651):  at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:73)
E/AndroidRuntime(17651):  at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:35)
E/AndroidRuntime(17651):  at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
E/AndroidRuntime(17651):  at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
E/AndroidRuntime(17651):  at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
E/AndroidRuntime(17651):  at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
E/AndroidRuntime(17651):  at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
E/AndroidRuntime(17651):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17651):  at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17651):  at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(17651):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17651):  at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17651):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(17651):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Thanks for your fast replies! And my apologies for my perseverance ;)

**Comment by mvarnagiris** [comment]
If you understand code, you can check DBMigration class. This should help you

**Comment by mvarnagiris** [comment]
OK so now I decided again not to support old backups. Even backups created on version lower than 0.14.x will not be supported. This is necessary to ensure that all Ids are truly unique.

**Comment by avbhanda** [comment]
Not sure this is a new bug or already reported one.  But app always crashes whenever I export/import (irrespective of GDrive or Folder).  Error gets presented whether the database is empty (with no account or transactions) or has multiple transactions with different accounts.

![screenshot_2014-11-08-23-55-51](https://cloud.githubusercontent.com/assets/132821/4965135/ddf7a20c-677e-11e4-8548-132d96bcc53e.png)

**Comment by mvarnagiris** [comment]
@avbhanda Just to confirm, the app crashes, but import/export succeeds?

**Comment by avbhanda** [comment]
Earlier revisions, Imp/Exp was successfull, but it does not succeed in latest revision.
